[package]
name = "EALD"
version = "0.1.0"
authors = ["urameshiya <20288123+urameshiya@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
lazy_static = "1.4.0"